/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package story;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {
        Movie endGame = new Movie();
        endGame.start();
    }
}



//    int random_int = (int)Math.floor(Math.random()*(max-min+1)+min);

//    Random rand = new Random(); //instance of random class
//    int upperbound = 25;
//    //generate random values from 0-24
//    int int_random = rand.nextInt(upperbound);
//    double double_random=rand.nextDouble();
//    float float_random=rand.nextFloat();

// Marvel

//

// Character
    //characteristic traits
  //get images of the characters
// movie comic

// Thanos snap fingers

// character class
//movie class reference the characters within the movie
//end game
    //thanos snap
    //thor's hammer?



// https://ascii.co.uk/art/hammer